### ISSUE TITLE
Add "barbershops" as a child under "health and beauty"

### ISSUE THREAD

**Issue by dpaa-committee** [openooh/venue-taxonomy#48] opened 2021-02-12 16:11 UTC
Can they add networks “barbershops”  as a child under parent of health and beauty. 

(Rouge Media via DPAA)

**Comment by christiancollins11** [comment] 2021-02-19 00:05
This seems redundant with https://github.com/openooh/venue-taxonomy/issues/22, and I'd rather handle it by subcategory.

**Comment by ndbabb** [comment] 2021-02-19 16:13
Agree with @christiancollins11 -- although perhaps a question as to whether "Men's Salon" and "Barbershops" are synonymous and which is a better term. @dpaa-committee, your thoughts?

**Comment by mowasfi7** [comment] 2021-02-19 16:45
Agree. This should live under Salons.

**Comment by dpaa-committee** [comment] 2021-02-19 17:12
@ndbabb The preference is "Barbershops"  thanks

**Comment by jayshao** [comment] 2021-02-23 14:20
Duplicate #22

**Comment by jayshao** [comment] 2021-02-23 14:21
I'm going to close this as a duplicate of #22

**Closed by jayshao** 2021-02-23 14:21 UTC
Labels: duplicate, enhancement
