### ISSUE TITLE
Add: Leisure -> Night Clubs

### ISSUE THREAD

**Issue by jayshao** [openooh/venue-taxonomy#16] opened 2020-10-14 18:03 UTC
Astral suggests adding Night Clubs to better represent their inventory. This is probably by virtue of their Montreal inventory.

**Comment by jayshao** [comment] 2020-10-14 18:22
This seems like a really interesting question. In the US, I think most mainstream advertisers avoid "adult" categories - so this might primarily be useful (in theory) for blocking, though in practice, most mainstream networks will exclude inventory like this entirely. (I can think of AdBrite and some other networks that got type cast into running on adult websites)

Not sure if internationally that might be more accepted/acceptable?

**Comment by mowasfi7** [comment] 2021-02-19 17:07
Duplicate of #15?

**Comment by bruno8g** [comment] 2021-02-22 22:51
I agree that buyers need a way to easily identify and exclude Gentlemen's Club. A lot of this is happening in Canada. As mentioned in #43 maybe using a "Sensitive Topics" or  "Restricted" Category. Not sure if there will be a lot of Sensitive categories, maybe adding a child Gentlemen's clubs to Entertainment is good enough. Could a dispensary be sensitive for some buyers?

**Comment by jayshao** [comment] 2021-02-23 14:30
@bruno8g I have been wondering the same thing. I think the social trends on that are changing across North America at least, but there are certainly parts of the world where I would think the answer would be very much so - and varying standards are I think the hardest part of determining "sensitive" globally - when we did the IAB Content Taxonomy, we were... much more US-centric, but I think the world has changed since then

**Comment by jayshao** [comment] 2021-02-23 14:34
We could also decide to take no position on that kind of rating in the venue category explicitly - and punt that to an offline conversation or a parallel "content rating/safety" standard - if this isn't a blocker for the way we want to handle forward compatibility

**Comment by jayshao** [comment] 2021-03-05 13:42
Added this as "night clubs" since that matched the original description (though not the original title) - probably worth seeing if that was the intent, or if we also might consider a category for "adult" clubs

**Comment by jayshao** [comment] 2021-03-05 16:46
Based on discussion on call - also looking to also add "gentleman's club"

**Closed** 2021-03-11 00:28 UTC
Labels: enhancement
